### ISSUE TITLE
Sitemap: No text links display to all pages

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#1]
![image](https://cloud.githubusercontent.com/assets/13363508/13594712/317720ba-e541-11e5-909a-c679b5e86484.png)

**Comment by euveng** [comment]
Fixed.

**Comment by maehtitan** [comment]
Hi @euveng,

This issue is all about sitemap which is empty and not in W3C Checking anymore.

Thanks

**Comment by euveng** [comment]
Sorry @maehtitan, my oversight. The fix has been done.
