### ISSUE TITLE
W3C - Walk-in Urgent Care : 40 Errors found.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#15]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Fwalk-in-urgent-care%2F

**Comment by maehtitan** [comment]
5 issues left

**Comment by jonathanza** [comment]
1 issue remaining. That item will not be fixed as it's required for a Safari favicon.
