### ISSUE TITLE
Home - newsletter: Form field background is supposed to be of different color and font weight.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Apollo-Health#19]
![image](https://cloud.githubusercontent.com/assets/11186313/13597264/89fd7ac0-e552-11e5-99c6-ea861dbae764.png)

**Comment by Sntax** [comment]
Unfortunately bootstrap does not allow for the multi-tiered background as shown in the design. Design has wavered this and ask that we choose the lighter colour for the newsletter background.

**Comment by roseliesromeo** [comment]
Change in implementation.
