### ISSUE TITLE
W3C - Privacy & Disclaimer: 38 Errors Found

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#22]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Fprivacy-disclaimer%2F

**Comment by maehtitan** [comment]
3 Errors left

**Comment by euveng** [comment]
1 issue remaining. That item will not be fixed as it's required for a Safari favicon.
