### ISSUE TITLE
Sidebar Opening Times: Ensure that if Business Details field has no value, then it should not display the respective heading for that specific field.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#37]
![image](https://cloud.githubusercontent.com/assets/12888048/13622768/fe794896-e5db-11e5-963b-c9f9b1cd471a.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13622769/009126c6-e5dc-11e5-8ea9-17090aaea4bc.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13622772/02ed2faa-e5dc-11e5-966c-c26f4569ffd6.png)

**Comment by euveng** [comment]
Fixed.

**Comment by jonathanza** [comment]
@romatitan - This looks fixed. Please confirm.
