### ISSUE TITLE
W3C - Iframe page: 4 Errors found. Is this really included in the site implementation?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#38]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Fiframe-page%2F

![image](https://cloud.githubusercontent.com/assets/13363508/13622569/87e797ec-e5da-11e5-886e-0dfde91a523a.png)

**Comment by jonathanza** [comment]
Hi,

Yes, unfortunately this site does include an iframe implementation. It's a requirement directly from the client.
