### ISSUE TITLE
W3C - Urgent Medical Care: 5 Errors found.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#39]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Fmedical-services%2Furgent-medical-care%2F

![image](https://cloud.githubusercontent.com/assets/13363508/13622671/44d94b5c-e5db-11e5-82be-29252788033e.png)

**Comment by euveng** [comment]
1 issue remaining. That item will not be fixed as it's required for a Safari favicon.
