### ISSUE TITLE
W3C - Book Your GP Appointment: 7 Errors found.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#40]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fapollohealth.stage.titanweb.com.au%2Fmedical-services%2Fbook-your-gp-appointment%2F

![image](https://cloud.githubusercontent.com/assets/13363508/13622733/bbe0aac4-e5db-11e5-8df0-28e32543aa0d.png)

**Comment by euveng** [comment]
1 issue remaining. That item will not be fixed as it's required for a Safari favicon.
