### ISSUE TITLE
General: A border line was automatically added below the H3 heading

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#42]
**Affected pages**: Contact Us
![image](https://cloud.githubusercontent.com/assets/12888048/13623137/427ffea6-e5df-11e5-9f3d-47f2d845661b.png)

**Comment by Sntax** [comment]
There's supppsed to be an hr below h3s on that page...

**Comment by roseliesromeo** [comment]
That is understandable for headings with H3 tags, but not for H3 within a body content.

**Comment by jonathanza** [comment]
Design has H3 title 'Call us' and 'Book online' I'm marking this as wontfix and closing.
