### ISSUE TITLE
Header Top Section: Spaces in between social media icons aren't match from the given design, currently they are too close to each other when there is more space in its right side area

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#45]
![image](https://cloud.githubusercontent.com/assets/13363508/13623348/fe93bb72-e5e0-11e5-82f3-fa152e10f5cc.png)

**Comment by Sntax** [comment]
To prevent the need for style changes in the future, spacing was reduced to allow for additional icons should the client ever need to add additional social media icons. Event though the design only reflects 3 icons, the site is coded to handle up to 5 icons as a precedent was set in a previous project. Please see line 22 on [the following technical assessment](https://docs.google.com/spreadsheets/d/1Xd6mHLYeehI7V49OseEXUGpGTI8F_J-ZyLrwieVGo1U/edit#gid=1914977935).
