### ISSUE TITLE
Homepage & Inner page banner has no fix height

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#47]
![image](https://cloud.githubusercontent.com/assets/12888048/13623631/eea24704-e5e2-11e5-8d81-32aee99f0ed3.png)

**Comment by romatitan** [comment]
**Not yet fixed on inner page banner**
![image](https://cloud.githubusercontent.com/assets/12888048/13661896/6fa3d482-e6d1-11e5-88dc-d4f0193cccbb.png)

**Comment by Sntax** [comment]
Fixed
