### ISSUE TITLE
Homepage - Banner: Incorrect font-size used in banner text

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#50]
![image](https://cloud.githubusercontent.com/assets/13363508/13624256/5c82630e-e5e7-11e5-9a44-9e2d32edb039.png)

**Comment by euveng** [comment]
The banner text is currently using H2 - should it be changed to H1 to follow the correct styling? Or should we avoid using H1 here, but style H2 instead?

**Comment by Sntax** [comment]
It was originally H1 but was switched to H2 in order to  maintain an H1 consistence within the body content.
