### ISSUE TITLE
Inner page banner:  Limit the banner title to its content area

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#51]
![image](https://cloud.githubusercontent.com/assets/12888048/13624265/7ee7f4f4-e5e7-11e5-807b-2b82dfa792c1.png)

**Comment by euveng** [comment]
The banner text is currently using H2 - should it be changed to H1 to follow the correct styling? Or should we avoid using H1 here, but style H2 instead?

**Comment by Sntax** [comment]
This would reduce the amount of space the client has to work with on their banners. Added some padding to improve the look on long strings.
