### ISSUE TITLE
Inner page banner: Banner title font size was set to 45px. It should be 40px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#54]
![image](https://cloud.githubusercontent.com/assets/12888048/13624561/4ddb51aa-e5ea-11e5-8ff4-ec72f924b5f0.png)

**Comment by euveng** [comment]
The banner text is currently using H2 - should it be changed to H1 to follow the correct styling? Or should we avoid using H1 here, but style H2 instead?

**Comment by Sntax** [comment]
It was originally H1 but was switched to H2 in order to maintain an H1 consistency within the body content and semantics.
