### ISSUE TITLE
Homepage - Lead-ins: Limit the repeater items to 4 only as per given design, so that it wont destroy the layout when newly added repeater is appended

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#58]
![image](https://cloud.githubusercontent.com/assets/13363508/13624993/1615b5e0-e5ee-11e5-9371-c6f0404bce6c.png)

**Comment by jonathanza** [comment]
Updated repeater to restrict it to 4 items only.
