### ISSUE TITLE
Search result: Font color item title aren't consistent between page 1 and page 2.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Apollo-Health#7]
![image](https://cloud.githubusercontent.com/assets/11186313/13596263/6aeed5e4-e54c-11e5-8270-cc8226ff2190.png)

**Comment by jonathanza** [comment]
Unable to replicate. Please provide testing term used to produce error or close ticket.

**Comment by roseliesromeo** [comment]
Steps used.
1. Key ex test in the search field
2. Check page 1 and page 2

But seems that issue no longer exists following the steps.
