### ISSUE TITLE
General: Contact Us should not be the parent breadcrumb of Thank you page. Remove "Contact Us" in the breadcrumb trails

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#72]
![image](https://cloud.githubusercontent.com/assets/12888048/13627122/0cc8ddf4-e603-11e5-8f90-c9ebbc7b2b1e.png)

**Comment by jonathanza** [comment]
The 'Thank You' page is a child of the 'Contact us' page. The breadcrumbs are correct.
