### ISSUE TITLE
Sign up to our newsletter: Heading background color should be #5b5f63, while the text labels and fields background color should be #74787b

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Apollo-Health#77]
![image](https://cloud.githubusercontent.com/assets/13363508/13627645/c1493b36-e606-11e5-9194-912f124a8589.png)

**Comment by Sntax** [comment]
You're using old PSDs. This isnt the case anymore. Please use the most recent PSDss

**Comment by jonathanza** [comment]
Closing duplicate issue.
