### ISSUE TITLE
Locations post / Locations sub page: Redundant pages

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Apollo-Health#95]
A sub pages for location was created. It only use the page title field and All post settings. Then, it use a page link for location post template.

If the purpose of creating sub pages for location is to be able to use the "All Post Settings", why not just display it on Location custom post? It seems possible because it was use on default post (news)

![image](https://cloud.githubusercontent.com/assets/12888048/13629338/78bdd356-e613-11e5-8dd2-fe449dfef427.png)
![image](https://cloud.githubusercontent.com/assets/12888048/13629342/7b2427a8-e613-11e5-9fad-5e05fac804ee.png)

**Comment by jonathanza** [comment]
The 'location' custom post type makes it easier to query for only the locations of a specific type. It's easy to query the custom post type than to query for a page with a specific template. 

The specific requirement to have the location as a sub-page is for SEO where the URL must be '/contact-us/armadale/' for example.
